package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AchievedBonuses generated by hbm2java
 */
@Entity
@Table(name = "ACHIEVED_BONUSES", catalog = "STAMPIT")
public class AchievedBonus implements java.io.Serializable {

	private long idAchievedBonuses;
	private ActiveCard activeCards;
	private Bonus bonus;

	public AchievedBonus() {
	}

	@Id
	@Column(name = "ID_ACHIEVED_BONUSES", unique = true, nullable = false)
	public long getIdAchievedBonuses() {
		return this.idAchievedBonuses;
	}

	public void setIdAchievedBonuses(long idAchievedBonuses) {
		this.idAchievedBonuses = idAchievedBonuses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTIVE_CARD")
	public ActiveCard getActiveCards() {
		return this.activeCards;
	}

	public void setActiveCards(ActiveCard activeCards) {
		this.activeCards = activeCards;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_BONUS")
	public Bonus getBonus() {
		return this.bonus;
	}

	public void setBonus(Bonus bonus) {
		this.bonus = bonus;
	}

}
