package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AchievedBonuses generated by hbm2java
 */
@Entity
@Table(name = "ACHIEVED_BONUSES", catalog = "STAMPIT")
public class AchievedBonus implements java.io.Serializable {

	private long idAchievedBonuses;
	private ActiveCard activeCard;
	private Bonus bonus;
	private boolean used;

	public AchievedBonus() {
	}


	@Id
//	@SequenceGenerator(name="ACHIEVED_BONUSES_ID_ACHIEVED_BONUSES_seq",
//		sequenceName="ACHIEVED_BONUSES_ID_ACHIEVED_BONUSES_seq",
//		allocationSize=1)
//	@GeneratedValue(strategy = GenerationType.SEQUENCE,
//		generator="ACHIEVED_BONUSES_ID_ACHIEVED_BONUSES_seq")
	@Column(name = "ID_ACHIEVED_BONUSES", unique = true, nullable = false)
	public long getIdAchievedBonuses() {
		return this.idAchievedBonuses;
	}

	public void setIdAchievedBonuses(long idAchievedBonuses) {
		this.idAchievedBonuses = idAchievedBonuses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_ACTIVE_CARD")
	public ActiveCard getActiveCard() {
		return this.activeCard;
	}

	public void setActiveCard(ActiveCard activeCard) {
		this.activeCard = activeCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_BONUS")
	public Bonus getBonus() {
		return this.bonus;
	}

	public void setBonus(Bonus bonus) {
		this.bonus = bonus;
	}

	@Column(name = "USED")
	public boolean isUsed() {
		return used;
	}

	public void setUsed(boolean used) {
		this.used = used;
	}		
	
}
