package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Cards generated by hbm2java
 */
@Entity
@Table(name = "CARDS", catalog = "STAMPIT")
public class Card {

	private Long idCard;	
	private Merchant merchants;
	private int slotsNum;
	private Date expireDate;	
	private Set<Code> codeses = new HashSet<Code>();	
	private Set<ActiveCard> activeCardses = new HashSet<ActiveCard>();	
	private Set<Bonus> bonuses = new HashSet<Bonus>();

	public Card() {
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)
//	@SequenceGenerator(name="CARDS_ID_CARD_seq",
//		sequenceName="CARDS_ID_CARD_seq",
//		allocationSize=1)
//	@GeneratedValue(strategy = GenerationType.SEQUENCE,
//		generator="CARDS_ID_CARD_seq")
	@Column(name = "ID_CARD", unique = true, nullable = false)
	public Long getIdCard() {
		return this.idCard;
	}

	public void setIdCard(Long idCard) {
		this.idCard = idCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MERCHANT", nullable = false)
	public Merchant getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchant merchants) {
		this.merchants = merchants;
	}

	@Column(name = "SLOTS_NUM", nullable = false)
	public int getSlotsNum() {
		return this.slotsNum;
	}

	public void setSlotsNum(int slotsNum) {
		this.slotsNum = slotsNum;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPIRE_DATE", nullable = false, length = 10)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<Code> getCodeses() {
		return this.codeses;
	}

	public void setCodeses(Set<Code> codeses) {
		this.codeses = codeses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<ActiveCard> getActiveCardses() {
		return this.activeCardses;
	}

	public void setActiveCardses(Set<ActiveCard> activeCardses) {
		this.activeCardses = activeCardses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "card")
	public Set<Bonus> getBonuses() {
		return this.bonuses;
	}

	public void setBonuses(Set<Bonus> bonuses) {
		this.bonuses = bonuses;
	}

}
