package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Codes generated by hbm2java
 */
@Entity
@Table(name = "CODES", catalog = "STAMPIT")
public class Code implements java.io.Serializable {

	private long idCode;	
	private Card cards;	
	private StampParameter stampParameters;
	private String code;

	public Code() {
	}

	public Code(long idCode, Card cards, StampParameter stampParameters,
			String code) {
		this.idCode = idCode;
		this.cards = cards;
		this.stampParameters = stampParameters;
		this.code = code;
	}

	@Id
	@Column(name = "ID_CODE", unique = true, nullable = false)
	public long getIdCode() {
		return this.idCode;
	}

	public void setIdCode(long idCode) {
		this.idCode = idCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_CARD", nullable = false)
	public Card getCards() {
		return this.cards;
	}

	public void setCards(Card cards) {
		this.cards = cards;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_STAMP_PARAMS", nullable = false)
	public StampParameter getStampParameters() {
		return this.stampParameters;
	}

	public void setStampParameters(StampParameter stampParameters) {
		this.stampParameters = stampParameters;
	}

	@Column(name = "CODE", nullable = false, length = 8000)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}
