package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MerchantFeedbacks generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT_FEEDBACKS", catalog = "STAMPIT")
public class MerchantFeedback implements java.io.Serializable {

	private long idFeedback;
	private Merchant merchants;
	private String message;
	private Date insDate;

	public MerchantFeedback() {
	}

	public MerchantFeedback(long idFeedback, String message, Date insDate) {
		this.idFeedback = idFeedback;
		this.message = message;
		this.insDate = insDate;
	}

	public MerchantFeedback(long idFeedback, Merchant merchants,
			String message, Date insDate) {
		this.idFeedback = idFeedback;
		this.merchants = merchants;
		this.message = message;
		this.insDate = insDate;
	}

	

	@Id
//	@SequenceGenerator(name="MERCHANT_FEEDBACKS_ID_FEEDBACK_seq",
//	sequenceName="MERCHANT_FEEDBACKS_ID_FEEDBACK_seq",
//	allocationSize=1)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE,
//	generator="MERCHANT_FEEDBACKS_ID_FEEDBACK_seq")
	@Column(name = "ID_FEEDBACK", unique = true, nullable = false)
	public long getidFeedback() {
		return this.idFeedback;
	}

	public void setIdFeedback(long idFeedback) {
		this.idFeedback = idFeedback;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MERCHANT")
	public Merchant getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchant merchants) {
		this.merchants = merchants;
	}

	@Column(name = "MESSAGE", nullable = false, length = 1000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INS_DATE", nullable = false, length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

}
