package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MerchantCategories generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT_CATEGORIES", catalog = "STAMPIT")
public class MerchantCategory implements java.io.Serializable {

	private long idCategory;
	private String name;
	private String description;
	private Set<StampParameter> stampParameterses = new HashSet<StampParameter>(0);
	private Set<Merchant> merchantses = new HashSet<Merchant>(0);

	public MerchantCategory() {
	}

	public MerchantCategory(long idCategory, String name) {
		this.idCategory = idCategory;
		this.name = name;
	}

	public MerchantCategory(long idCategory, String name, String description,
			Set stampParameterses, Set merchantses) {
		this.idCategory = idCategory;
		this.name = name;
		this.description = description;
		this.stampParameterses = stampParameterses;
		this.merchantses = merchantses;
	}

	@Id
	@Column(name = "ID_CATEGORY", unique = true, nullable = false)
	public long getIdCategory() {
		return this.idCategory;
	}

	public void setIdCategory(long idCategory) {
		this.idCategory = idCategory;
	}

	@Column(name = "NAME", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "DESCRIPTION", length = 1000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "categories_params", catalog = "stampit", joinColumns = { @JoinColumn(name = "ID_CATEGORY", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "ID_PARAM", nullable = false, updatable = false) })
	public Set<StampParameter> getStampParameterses() {
		return this.stampParameterses;
	}

	public void setStampParameterses(Set<StampParameter> stampParameterses) {
		this.stampParameterses = stampParameterses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "merchantCategories")
	public Set<Merchant> getMerchantses() {
		return this.merchantses;
	}

	public void setMerchantses(Set<Merchant> merchantses) {
		this.merchantses = merchantses;
	}

}
