package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * MerchantFeedbacks generated by hbm2java
 */
@Entity
@Table(name = "MERCHANT_FEEDBACKS", catalog = "STAMPIT")
public class MerchantFeedback implements java.io.Serializable {

	private long idFeedbaack;
	private Merchant merchants;
	private String message;
	private Date insDate;

	public MerchantFeedback() {
	}

	public MerchantFeedback(long idFeedbaack, String message, Date insDate) {
		this.idFeedbaack = idFeedbaack;
		this.message = message;
		this.insDate = insDate;
	}

	public MerchantFeedback(long idFeedbaack, Merchant merchants,
			String message, Date insDate) {
		this.idFeedbaack = idFeedbaack;
		this.merchants = merchants;
		this.message = message;
		this.insDate = insDate;
	}

	@Id
	@Column(name = "ID_FEEDBAACK", unique = true, nullable = false)
	public long getIdFeedbaack() {
		return this.idFeedbaack;
	}

	public void setIdFeedbaack(long idFeedbaack) {
		this.idFeedbaack = idFeedbaack;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_MERCHANT")
	public Merchant getMerchants() {
		return this.merchants;
	}

	public void setMerchants(Merchant merchants) {
		this.merchants = merchants;
	}

	@Column(name = "MESSAGE", nullable = false, length = 1000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INS_DATE", nullable = false, length = 19)
	public Date getInsDate() {
		return this.insDate;
	}

	public void setInsDate(Date insDate) {
		this.insDate = insDate;
	}

}
