package com.stampit.model;

// Generated 1-ago-2014 11.47.35 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Prizes generated by hbm2java
 */
@Entity
@Table(name = "PRIZES", catalog = "STAMPIT")
public class Prize implements java.io.Serializable {

	private long idPrize;
	private String description;
	private Set<Bonus> bonuses = new HashSet<Bonus>(0);

	public Prize() {
	}

	public Prize(long idPrize, String description) {
		this.idPrize = idPrize;
		this.description = description;
	}

	public Prize(long idPrize, String description, Set<Bonus> bonuses) {
		this.idPrize = idPrize;
		this.description = description;
		this.bonuses = bonuses;
	}

	
	@Id
//	@SequenceGenerator(name="PRIZES_ID_PRIZE_seq",
//	sequenceName="PRIZES_ID_PRIZE_seq",
//	allocationSize=1)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE,
//	generator="PRIZES_ID_PRIZE_seq")
	@Column(name = "ID_PRIZE", unique = true, nullable = false)
	public long getIdPrize() {
		return this.idPrize;
	}

	public void setIdPrize(long idPrize) {
		this.idPrize = idPrize;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prizes")
	public Set<Bonus> getBonuses() {
		return this.bonuses;
	}

	public void setBonuses(Set<Bonus> bonuses) {
		this.bonuses = bonuses;
	}

}
